//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Wypozyczenia
    {
        public int IdUcznia { get; set; }
        public int IdKsiazki { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public Nullable<System.DateTime> DataOddania { get; set; }
    
        public virtual Ksiazki Ksiazki { get; set; }
        public virtual Uczniowie Uczniowie { get; set; }
    }
}
